name: VPN Connection

on:
  push:
    branches: [ main ]

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install OpenVPN
        run: |
          sudo apt-get update 
          sudo apt-get install -y openvpn
          sudo apt install -y openvpn openvpn-systemd-resolved
     
      
      - name: Download VPN configuration files
        run: |
          wget ftp://ftp.infradead.org/pub/openconnect/openconnect-8.00.tar.gz
          sudo tar xvf openconnect-8.00.tar.gz
          cd openconnect-8.00
          sudo apt install libssl-dev pkg-config libxml2-dev zlib1g-dev

          sudo ./configure --disable-nls
          --with-vpnc-script=/etc/vpnc/vpnc-script
        
      - name: Connect to VPN using OpenVPN
        run: |
  
          sudo openvpn --config vpn-config/config.ovpn --cert ./client.crt --key ./client.key

      
      - name: Start VPN connection
        run: |
          sudo openvpn /etc/openvpn/config/vpn.conf
